### ISSUE TITLE
error: wrong index v2 file size

### ISSUE THREAD

**Issue by fionera** [not-an-aardvark/every-git-commit-shorthash#1]
Hi,

I tried using your release Files but got the following Errors:
```
error: wrong index v2 file size in .git/objects/pack/pack-every-shorthash.idx
error: wrong index v2 file size in .git/objects/pack/pack-every-shorthash.idx
error: wrong index v2 file size in .git/objects/pack/pack-every-shorthash.idx
error: wrong index v2 file size in .git/objects/pack/pack-every-shorthash.idx
fatal: update_ref failed for ref 'refs/heads/every-shorthash': cannot update ref 'refs/heads/every-shorthash': trying to write ref 'refs/heads/every-shorthash' with nonexistent object 68bee79b595699fca8a6bb786b52f8cf070f19bd
```

I also tried creating my own files by running the software, but the output has the same issue.

**Comment by not-an-aardvark** [comment]
Thanks for the report. What version of git are you using? From briefly looking just now, my understanding is that git 2.30.0 fixed some bugs relating to very large packfiles (e.g. https://github.com/git/git/commit/f86f769550ef7fb5162a9cd4be5e2be7981d063b). If your git version is older than 2.30.0, then updating git might fix the issue.

**Comment by fionera** [comment]
Yes that was the issue, thank you <3
